parameters:
    wa_back_bundle.util.utility.class: Wa\BackBundle\Util\Utility
    wa_back_bundle.panier.class: Wa\BackBundle\Services\Cart
    competences:
        php: 1
        html: 9
        css: 4
    genders:
        0: Homme
        1: Femme
    maintenance: false

services:
    wa_back.util:
        class: %wa_back_bundle.util.utility.class%
        arguments: [%competences%, "ceci est un texte", @doctrine.orm.entity_manager]

    wa_back_panier:
        class: %wa_back_bundle.panier.class%
        arguments: [@doctrine.orm.entity_manager, @session]

    troiswa.validator.position.category:
        class: Wa\BackBundle\Validator\PositionCategoryValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: troiswa_back_position_category }

    troiswa.type.gendertype:
        class: Wa\BackBundle\Form\Type\GenderType
        arguments: [%genders%]
        tags:
            - { name: form.type, alias: gender }

    troiswa.maintenance:
        class: Wa\BackBundle\Listener\Maintenance
        arguments: [@twig, %maintenance%, %kernel.environment%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: miseEnMaintenance }

#importer d'autre services.yml dans service
#imports:
    #- { resource: servicesbidule.yml }