wa_back_categorie_index:
    path: /index
    defaults: { _controller: WaBackBundle:Categorie:index }

wa_back_categorie_list:
    path: /list
    defaults: { _controller: WaBackBundle:Categorie:list }

wa_back_categorie_edit:
    path: /edit/{id}
    defaults: { _controller: WaBackBundle:Categorie:edit }
    requirements:
        id: \d+

wa_back_categorie_show:
    path: /show/{id}
    defaults: { _controller: WaBackBundle:Categorie:show }
    requirements:
        id: \d+

wa_back_categorie_create:
    path: /create
    defaults: { _controller: WaBackBundle:Categorie:create }

wa_back_categorie_delete:
    path: /delete/{id}
    defaults: { _controller: WaBackBundle:Categorie:delete }