wa_back_produit_list:
    path: /list
    defaults: { _controller: WaBackBundle:Produit:list }

wa_back_produit_edit:
    path: /edit/{id}
    defaults: { _controller: WaBackBundle:Produit:edit }

wa_back_produit_show:
    path: /show/{id}
    defaults: { _controller: WaBackBundle:Produit:show }

wa_back_produit_create:
    path: /create
    defaults: { _controller: WaBackBundle:Produit:create }

wa_back_produit_delete:
    path: /delete/{id}
    defaults: { _controller: WaBackBundle:Produit:delete }