<?php

namespace Wa\BackBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBrandOrderByTitleAsc(){
        return $this->createQueryBuilder('m')->orderBy('m.title', 'ASC');
    }

}
