<?php

namespace Wa\BackBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMarqueOrderByTitleAsc(){
        return $this->createQueryBuilder('m')->orderBy('m.title', 'ASC');
    }

}
