wa_back_brand:
    path:     /list/{page}
    defaults: { _controller: "WaBackBundle:Brand:index", page: 1 }
    requirements:
        page: \d+

wa_back_brand_show:
    path:     /show/{id}
    defaults: { _controller: "WaBackBundle:Brand:show" }

wa_back_brand_new:
    path:     /new
    defaults: { _controller: "WaBackBundle:Brand:new" }

wa_back_brand_create:
    path:     /create
    defaults: { _controller: "WaBackBundle:Brand:create" }
    methods:  POST

wa_back_brand_edit:
    path:     /edit/{id}
    defaults: { _controller: "WaBackBundle:Brand:edit" }

wa_back_brand_update:
    path:     /update/{id}
    defaults: { _controller: "WaBackBundle:Brand:update" }
    methods:  [POST, PUT]

wa_back_brand_delete:
    path:     /delete/{id}
    defaults: { _controller: "WaBackBundle:Brand:delete" }
    methods:  [GET]