wa_back_comment_active:
    path: /reactive/{id}
    defaults: { _controller: WaBackBundle:Comment:active }
    requirements:
        id: \d+
        active: \d+

wa_back_comment_index:
    path: /index
    defaults: { _controller: WaBackBundle:Comment:index }

wa_back_comment_list:
    path: /list/{page}
    defaults: { _controller: WaBackBundle:Comment:list, page: 1 }

wa_back_comment_edit:
    path: /edit/{id}
    defaults: { _controller: WaBackBundle:Comment:edit }
    requirements:
        id: \d+

wa_back_comment_show:
    path: /show/{id}
    defaults: { _controller: WaBackBundle:Comment:show }
    requirements:
        id: \d+

wa_back_comment_create:
    path: /create
    defaults: { _controller: WaBackBundle:Comment:create }

wa_back_comment_delete:
    path: /delete/{id}
    defaults: { _controller: WaBackBundle:Comment:delete }