wa_back_marque:
    path:     /
    defaults: { _controller: "WaBackBundle:Marque:index" }

wa_back_marque_show:
    path:     /{id}/show
    defaults: { _controller: "WaBackBundle:Marque:show" }

wa_back_marque_new:
    path:     /new
    defaults: { _controller: "WaBackBundle:Marque:new" }

wa_back_marque_create:
    path:     /create
    defaults: { _controller: "WaBackBundle:Marque:create" }
    methods:  POST

wa_back_marque_edit:
    path:     /{id}/edit
    defaults: { _controller: "WaBackBundle:Marque:edit" }

wa_back_marque_update:
    path:     /{id}/update
    defaults: { _controller: "WaBackBundle:Marque:update" }
    methods:  [POST, PUT]

wa_back_marque_delete:
    path:     /{id}/delete
    defaults: { _controller: "WaBackBundle:Marque:delete" }
    methods:  [POST, DELETE]
