wa_back_product_index:
    path: /index/{page}
    defaults: { _controller: WaBackBundle:Product:index, page: 1 }

wa_back_product_list:
    path: /list/{page}
    defaults: { _controller: WaBackBundle:Product:list, page: 1 }

wa_back_product_edit:
    path: /edit/{id}
    defaults: { _controller: WaBackBundle:Product:edit }

wa_back_product_show:
    path: /show/{id}
    defaults: { _controller: WaBackBundle:Product:show }
    requirements:
        id: \d+

wa_back_product_create:
    path: /create
    defaults: { _controller: WaBackBundle:Product:create }

wa_back_product_delete:
    path: /delete/{id}
    defaults: { _controller: WaBackBundle:Product:delete }